# Generated by Django 4.2.5 on 2023-09-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',  # Make sure this matches the actual model name
            name='link',
            field=models.URLField(blank=True),  # You can adjust the field options as needed
        ),
    ]
